language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
#  - "3.8-dev"
# command to install dependencies
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y libgphoto2-dev
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest -v
